[project]
name = "OpenStudioLandscapes-filebrowser"
description = "filebrowser Feature for OpenStudioLandscapes"

[project.urls]
Homepage = "https://github.com/michimussato/OpenStudioLandscapes-filebrowser"

[project.optional-dependencies]
sbom = [
    "OpenStudioLandscapes-filebrowser[graphviz]",
]
nox = [
    "OpenStudioLandscapes-filebrowser[testing]",
]
dev = [
    "OpenStudioLandscapes-filebrowser[testing]",
    "OpenStudioLandscapes-filebrowser[lint]",
    "OpenStudioLandscapes-filebrowser[nox]",
    "OpenStudioLandscapes-filebrowser[sbom]",
    "OpenStudioLandscapes-filebrowser[coverage]",
    "OpenStudioLandscapes-filebrowser[readme]",
]

[tool.setuptools]
packages = [
    "OpenStudioLandscapes.filebrowser"
]

[tool.dagster]
module_name = "OpenStudioLandscapes.filebrowser.definitions"
code_location_name = "OpenStudioLandscapes-filebrowser"
