# Base Information
group_name: "OpenStudioLandscapes_filebrowser"
key_prefixes:
  - "OpenStudioLandscapes_filebrowser"

#compose_scope: "default"

#enabled: true

#filebrowser_port_container: 80
#filebrowser_port_host: 8080

#filebrowser_docker_image: "docker.io/filebrowser/filebrowser"

#filebrowser_shared_dir_permission: "rw"

#filebrowser_shared_dir: "{DOT_LANDSCAPES}/{LANDSCAPE}/{FEATURE}/shared"

#filebrowser_db_dir: "{DOT_LANDSCAPES}/{LANDSCAPE}/{FEATURE}/configs/filebrowser_db"

#filebrowser_json: "{DOT_LANDSCAPES}/{LANDSCAPE}/{FEATURE}/configs/filebrowser.json"
