# Base Information
group_name: "OpenStudioLandscapes_filebrowser"
key_prefixes:
  - "OpenStudioLandscapes_filebrowser"

compose_scope: "default"

# filebrowser_port_container: 80
filebrowser_port_host: 8080

filebrowser_db_dir: "{DOT_LANDSCAPES}/{LANDSCAPE}/{FEATURE}/configs/filebrowser_db"

filebrowser_root_permission: rw
